---
driver:
  name: openstack

provisioner:
  name: chef_zero
  chef_omnibus_url: <%= ENV['CHEF_OMNIBUS_URL'] %>
  require_chef_omnibus: <%= ENV['CHEF_OMNIBUS_VER'] %>
  client_rb:
    no_proxy: "localhost,127.0.0.1,10.*"

platforms:
  -
    driver_config:
      openstack_username: <%= ENV['OS_USERNAME'] %>
      openstack_api_key: <%= ENV['OS_PASSWORD'] %>
      insecure: true
      disable_ssl_validation: true
      openstack_auth_url: <%= ENV['OS_AUTH_URL'] %>/tokens
      key_name: <%= ENV['KEY_NAME'] %>
      openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
      floating_ip_pool: <%= ENV['FLOATING_IP_POOL'] %>
      private_key_path: <%= ENV['SSH_KEY_FILE'] %>
      image_ref: <%= ENV['OS_IMAGE_REF'] %>
      flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>
      network_ref: <%= ENV['OS_NETWORK_REF'] %>
      username: <%= ENV['OS_IMAGE_USER'] %>
    name: <%= ENV['OS_PLATFORM_NAME'] %>
    driver_plugin: openstack

suites:
  - name: artifactory-oracle
    run_list:
      - recipe[java::default]
      - recipe[artifactory::default]
    attributes:
      java:
        jdk_version: "7"
        oracle:
          accept_oracle_download_terms: true
        install_flavor: oracle
